# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - af-backend

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://afazcr.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_2942dd6e1b0247f38574fb19facf275f }}
        password: ${{ secrets.AzureAppService_ContainerPassword_0cf0c9b99cb644cc947ea5b2bdb94c09 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: afazcr.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_2942dd6e1b0247f38574fb19facf275f }}/af-backend:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'af-backend'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_c13dfe7e840b45358c42170e4e0fbd08 }}
        images: 'afazcr.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_2942dd6e1b0247f38574fb19facf275f }}/af-backend:${{ github.sha }}'